name: sam_segmentation_curvature

channels:
  - mosaic

dependencies:
  - python=3.7.*
  - numpy
  - matplotlib
  - jupyter
  - timagetk
  - cellcomplex
  - draco_stem
  - tissue_nukem_3d
  - tissue_analysis
  - sam_atlas
  - visu_core
  - panel
